# Generated by Django 3.2.18 on 2023-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('O', 'Other'), ('F', 'Female'), ('M', 'Male')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.FileField(upload_to='Teacher/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teachermobile',
            field=models.CharField(max_length=300),
        ),
    ]
